from __future__ import annotations

import argparse
import csv
from pathlib import Path

DEFAULT_SCALE_CSV = Path("paper/figures/results_by_run_scale.csv")
DEFAULT_SWEEP_CSV = Path("paper/figures/results_1000_threshold_sweep.csv")
DEFAULT_SCALE_TEX = Path("paper/figures/table_run_scale.tex")
DEFAULT_SWEEP_TEX = Path("paper/figures/table_threshold_sweep.tex")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build LaTeX table fragments from aggregated paper CSV outputs.")
    p.add_argument("--scale-csv", type=Path, default=DEFAULT_SCALE_CSV)
    p.add_argument("--sweep-csv", type=Path, default=DEFAULT_SWEEP_CSV)
    p.add_argument("--scale-tex", type=Path, default=DEFAULT_SCALE_TEX)
    p.add_argument("--sweep-tex", type=Path, default=DEFAULT_SWEEP_TEX)
    return p.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing CSV input: {path}")
    with path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"CSV contains no rows: {path}")
    return rows


def pct(value: str) -> str:
    return f"{float(value) * 100:.1f}"

def tex_escape(text: str) -> str:
    return text.replace("_", "\\_")


def write_scale_table(path: Path, rows: list[dict[str, str]]) -> None:
    lines = [
        "% Auto-generated by scripts/make_paper_figures.py",
        "\\begin{tabular}{lccccccc}",
        "\\toprule",
        "Run & Threshold & N & Coverage & Silence & Accepted Prec. & Risk Capture & Drift Sep. \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{tex_escape(r['run_label'])} & {r['silence_threshold']} & {r['task_count']} & "
            f"{pct(r['coverage'])}\\% & {pct(r['silence_rate'])}\\% & {pct(r['accepted_precision'])}\\% & "
            f"{pct(r['risk_capture'])}\\% & {float(r['drift_separation']):.2f}x \\\\",
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_sweep_table(path: Path, rows: list[dict[str, str]]) -> None:
    lines = [
        "% Auto-generated by scripts/make_paper_figures.py",
        "\\begin{tabular}{lcccccccc}",
        "\\toprule",
        "Run & Threshold & Coverage & Silence & Accepted Prec. & Risk Capture & Silenced Raw Success & Drift Accepted & Drift Silenced \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{tex_escape(r['run_label'])} & {r['silence_threshold']} & {pct(r['coverage'])}\\% & "
            f"{pct(r['silence_rate'])}\\% & {pct(r['accepted_precision'])}\\% & {pct(r['risk_capture'])}\\% & "
            f"{r['silenced_raw_success_count']} & {float(r['avg_drift_accepted']):.3f} & {float(r['avg_drift_silenced']):.3f} \\\\",
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    scale_rows = load_rows(args.scale_csv)
    sweep_rows = load_rows(args.sweep_csv)
    write_scale_table(args.scale_tex, scale_rows)
    write_sweep_table(args.sweep_tex, sweep_rows)
    print(f"Wrote LaTeX table fragment: {args.scale_tex}")
    print(f"Wrote LaTeX table fragment: {args.sweep_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
